feat: add application notes for admin
imperial/ug-admissions pull request #11
Opened 2024-09-16 10:14 UTC by zaki-amin

Add storage and the ability for admins to view extenuating circumstances and academic eligibility notes for an application

**UI**
- Add popover to AdminScoringDialog which displays extenuating circumstances when clicked. Popover only appears when the extenuating circumstances exist.
  - ![Screenshot 2024-09-16 at 11 10 30](https://github.com/user-attachments/assets/088feb72-1b87-4e01-8b7a-a4fb1795eff8)
  - ![Screenshot 2024-09-16 at 11 10 47](https://github.com/user-attachments/assets/ea8ab8c4-4a26-4b42-846e-212c6759177b)
- Add similar popover to AdminScoringDialog which displays academic eligibility notes when clicked.
  - ![Screenshot 2024-09-16 at 11 10 56](https://github.com/user-attachments/assets/67bd7f98-288e-4aa4-a5cc-1c6c0337ffda)

**Server**
- Prisma migrations to add extenuating circumstances and academic eligibility notes to the schema

_N.B._ once merged, the CSV upload will need to pass through the correct data

2024-09-16 11:46 UTC, IlliaDerevianko commented on prisma/schema/application.prisma
> +  academicEligibilityNotes String?
We are, will fix this

2024-09-16 13:15 UTC, IlliaDerevianko commented on prisma/schema/application.prisma
> +  academicEligibilityNotes String?
fixed in 93b7f9df1426c19b859d5ea5962892f357e3b8a6

2024-09-16 13:18 UTC, IlliaDerevianko commented on package.json
> +    "react-icons": "^5.3.0",
Yeah, we couldn't find a book icon there so we decided to use a bootstrap icon

2024-09-16 13:53 UTC, procaconsul commented on package.json
> +    "react-icons": "^5.3.0",
I hear you. I would be inclined to keep extra dependencies to a minimum, as each dep has a direct impact on build time etc. Could we use the Bookmark Filled perhaps? Or the File Text one, as notes?

2024-09-16 13:58 UTC, zaki-amin commented on package.json
> +    "react-icons": "^5.3.0",
Yeah we'll find some appropriate icons in the Radix React Icons to avoid an extra package

2024-09-16 14:53 UTC, zaki-amin commented on package.json
> +    "react-icons": "^5.3.0",
resolved in 90f8dfc1436d57655a0dec4d1387518b18dbb130

2024-09-17 10:02 UTC, IlliaDerevianko requested changes
A few small changes related to get rid of redundancy

2024-09-17 10:02 UTC, IlliaDerevianko commented on components/AdminScoringDialog.tsx
> +            defaultValue={parseFloat(internalReview?.extracurricularAdminScore?.toString() ?? '')}
```suggestion
            defaultValue={parseFloat(internalReview?.extracurricularAdminScore?.toString())}
```

2024-09-17 10:30 UTC, merged