refactor: form dialog
imperial/ug-admissions pull request #7
Opened 2024-09-10 09:24 UTC by IlliaDerevianko

- Extract dialog and form logic into separate components
- Use these components for AdminScoringForm

2024-09-10 10:28 UTC, procaconsul requested changes
Nice work! I have left plenty of meaty comments. I have numbered them 1 to 3 so it's easier to follow the logic behind the suggestions.

2024-09-10 10:28 UTC, procaconsul commented on components/GenericFormDialog.tsx
(1) This is overall _just_ a Dialog, if you think about it. How about:

- calling this `GenericDialog`
- turn `children` to `trigger`
- turn `form` to `children` and generalise the logic to decouple it from forms altogether

2024-09-10 10:28 UTC, procaconsul commented on components/FormInDialog.tsx
(2) Here I would: 

- collapse `close` and `closeOnSuccess` in a single prop called `onSuccess`, i.e. an _optional_ callback to call on success which defaults to `() => {}`
- rename the component to `FormWrapper`, and decouple it from the notion of dialog (as at this point there's no tie to a dialog: it's just a super Form that handles an action seamlessly and places the buttons at the bottom of the form

2024-09-10 10:28 UTC, procaconsul commented on components/FormInDialog.tsx
> +            {pending ? <Spinner /> : (submitButtonText ?? 'Save')}{' '}
```suggestion
            {pending ? <Spinner /> : (submitButtonText ?? 'Save')}
```

I would also extract 'Save' in a constant, like DEFAULT_SUBMIT_BTN_TEXT

2024-09-10 10:28 UTC, procaconsul commented on components/AdminScoringDialog.tsx
> +  )
(3) I would keep this component but:

- change `row` to `formData`
- extract at THIS level the form action i.e. `upsertAdminScoringWithId`
- compose the components as below:

```
<GenericDialog>
    <FormWrapper action={upsertAdminScoringWithId}>
        <AdminScoringForm data={data}/>
     </FormWrapper>
</GenericDialog>
```

2024-09-10 15:58 UTC, IlliaDerevianko commented on components/GenericFormDialog.tsx
Regarding turning 'form' to 'children', I would need to pass the close function to children. Is there a nice way to pass props to 'children' and keep its type as ReactNode?

2024-09-11 00:00 UTC, procaconsul commented on components/GenericFormDialog.tsx
Oooops you are right, sorry. I have expaned my point (3) to answer this question.

2024-09-11 00:02 UTC, procaconsul requested changes
More generic comment regarding style: I'll stay consistent with direct imports from React  e.g.

- `FC` instead of `React.FC`
- `useState` instead of `React.useState` etc.

2024-09-12 09:31 UTC, merged